# Generated by Django 3.1.3 on 2023-03-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guide', '0012_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='pending', max_length=30, null=True),
        ),
    ]
