# Generated by Django 3.1.3 on 2023-03-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guide', '0013_auto_20230329_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
