# Generated by Django 3.1.3 on 2023-04-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guide', '0014_auto_20230329_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_man',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='service_man',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
