# Generated by Django 3.1.3 on 2023-04-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guide', '0015_auto_20230402_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sentiment_score',
            field=models.FloatField(null=True),
        ),
    ]
