# Generated by Django 3.1.3 on 2023-04-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guide', '0016_contact_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
