# Generated by Django 3.1.3 on 2023-04-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guide', '0017_auto_20230402_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='desc',
        ),
    ]
